version: '3'
services:
  jekyll:
    image: jekyll/jekyll:builder
    container_name: schebotar-homepage
    command: jekyll serve --watch --incremental
    ports:
        - 4000:4000
    volumes:
        - .:/srv/jekyll